name: Update JSON

on:
  schedule:
  # run now
  - cron:  '*/1 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Select JSON
        # send content variable to index.html
        run: echo "::set-output name=JSON::$(cat data.json)"


      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update data.json"
          git push
