name: Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every night at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Select JSON
        run: echo "{\"name\": \"New Object\"}" > data.json

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update data.json"
          git push
