name: Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every night at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Select JSON
        run: echo "::set-output name=JSON::$(curl -s https://api.github.com/repos/leabs/guess-the-phrase/contents/data.json | jq -r '.content' | base64 -d)"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update data.json"
          git push
